### Creating the model

In [2]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import  LinearRegression

In [3]:
df = pd.read_csv('area_prices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
df.isnull().sum()

area     0
price    0
dtype: int64

In [5]:
model = LinearRegression()

In [6]:
model.fit(df[['area']], df['price'])

LinearRegression()

In [7]:
print(model.coef_)
print("\n")
print(model.intercept_)

[135.78767123]


180616.43835616432


In [8]:
model.predict([[5000]])

array([859554.79452055])

We can save the model separately so that every time we need a prediction, we need not train the model again and again. this helps to achieve consistency in results. 
Also, only the model can be exported in case we need it to send to someone

## saving model using pickle

In [9]:
import pickle

In [10]:
with open('model_pickle', 'wb') as f:
#         ("file name" , w = write mode / r = read mode and b = binary)    
#                      (so 'wb' means write in binary)
    pickle.dump(model , f)    # (model or whatever you want to dump, destination file i.e. dump into)

## saving model using sklearn joblib

there is no major difference in the functioality of pickle and joblib.
in sklearn documentation, it is recommended to prefer joblib if the dataset contains many numpy arrays

In [14]:
# from sklearn.externals import joblib
# if the above line shows error.... import only joblib directly

import joblib

In [15]:
joblib.dump(model, 'model_joblib')

['model_joblib']

## Opening the models

In [17]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [22]:
mp.predict([[5000]])

array([859554.79452055])

In [23]:
with open('model_joblib','rb') as f:
    mj = joblib.load(f)

In [24]:
mj.predict([[5000]])

array([859554.79452055])