technique used to evaulate and compare the performance of different models

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digits['data'], digits['target'], test_size = 0.2)

### 1. Logistic Regression

In [5]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

### 2. Support Vector Classifier

In [6]:
svc = SVC()
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

0.9833333333333333

### 3. Random Forest Classifier

In [7]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975

Here, if we rerun the train_test_split code, the accuracy score of all models will change.

So, in cases like these where there is very  little difference in accuracy scores (and that too might change everytime!!!), We cannot say that any particular model performs better than others.

In [8]:
from sklearn.model_selection import KFold

In [17]:
kf = KFold(n_splits = 3) # creating 3 folds

In [18]:
## Demo Example:

for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(f"training folds include: {train_index}, testing fold includes: {test_index}")

training folds include: [3 4 5 6 7 8], testing fold includes: [0 1 2]
training folds include: [0 1 2 6 7 8], testing fold includes: [3 4 5]
training folds include: [0 1 2 3 4 5], testing fold includes: [6 7 8]


In [21]:
def get_score(model, X_train, X_test, y_train, y_test ):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [24]:
print(f"Score of Logistic regression is: {get_score(LogisticRegression(), X_train, X_test, y_train, y_test)}")
print(f"Score of SVC is: {get_score(SVC(), X_train, X_test, y_train, y_test)}")
print(f"Score of Random Forest Classifier is: {get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)}")

## Nothing New... just a generic function to give the score of all above model without explicitly instantiating and fitting each 
## model individually

C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Score of Logistic regression is: 0.9666666666666667
Score of SVC is: 0.9833333333333333
Score of Random Forest Classifier is: 0.9777777777777777


### K fold Model

In [25]:
from sklearn.model_selection import StratifiedKFold

StratifiedKFold is similar to KFold, but slightly better in a way that it uniformly distributes each of the classification categories among all the folds (leaves little or no scope for biasness)

The working of both is same

In [26]:
folds = StratifiedKFold(n_splits = 3)

In [55]:
scores_lr = []
scores_svc = []
scores_rf = []

i = 0
for train_index, test_index in kf.split(digits['data']):
    X_train, X_test, y_train, y_test =  digits['data'][train_index],\
                                        digits['data'][test_index],\
                                        digits['target'][train_index],\
                                        digits['target'][test_index]
    i+=1
    print('iteration No.', i)
    
    scores_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svc.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 25), X_train, X_test, y_train, y_test))
    
    print(f"Score of Logistic regression is: {get_score(LogisticRegression(), X_train, X_test, y_train, y_test)}")
    print(f"Score of SVC is: {get_score(SVC(), X_train, X_test, y_train, y_test)}")
    print(f"Score of Random Forest Classifier is: {get_score(RandomForestClassifier(n_estimators = 25), X_train, X_test, y_train, y_test)}")
    
print("\n\n")   


iteration No. 1


C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Score of Logistic regression is: 0.9232053422370617
Score of SVC is: 0.9666110183639399
Score of Random Forest Classifier is: 0.9248747913188647
iteration No. 2


C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Score of Logistic regression is: 0.9415692821368948
Score of SVC is: 0.9816360601001669
Score of Random Forest Classifier is: 0.9432387312186978
iteration No. 3


C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Score of Logistic regression is: 0.9148580968280468
Score of SVC is: 0.9549248747913188
Score of Random Forest Classifier is: 0.9148580968280468





In [56]:
print(f"Final Logistic Regression Scores:{scores_lr}")
print(f"Final SVC Scores:{scores_svc}")
print(f"Final Random Forest Classifier Scores:{scores_rf}")

Final Logistic Regression Scores:[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
Final SVC Scores:[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
Final Random Forest Classifier Scores:[0.9215358931552587, 0.9398998330550918, 0.9215358931552587]


the Above code looks a bit messy and is written only for better understanding

sklearn has a method for the exact same thing (i.e. cross_val_score)

In [36]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [46]:
folds = StratifiedKFold(n_splits = 10)

In [47]:
cross_val_score(LogisticRegression(), digits['data'], digits['target'])

C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Manoj\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [48]:
cross_val_score(SVC(), digits['data'], digits['target'])

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [49]:
cross_val_score(RandomForestClassifier(), digits['data'], digits['target'])

array([0.93055556, 0.90833333, 0.95821727, 0.97214485, 0.9275766 ])

Here, we compared different Models / Classifiers

But we can also compare the same model / classifier with different parameters for fine tuning

In [57]:
cross_val_score(RandomForestClassifier(), digits['data'], digits['target'])

array([0.93611111, 0.92222222, 0.95821727, 0.96100279, 0.92479109])

In [58]:
cross_val_score(RandomForestClassifier(n_estimators = 10), digits['data'], digits['target'])

array([0.91666667, 0.85833333, 0.90529248, 0.9275766 , 0.8718663 ])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators = 50), digits['data'], digits['target'])

array([0.93055556, 0.92777778, 0.95821727, 0.95264624, 0.92479109])

In [60]:
cross_val_score(RandomForestClassifier(n_estimators = 100), digits['data'], digits['target'])

array([0.93888889, 0.90277778, 0.96100279, 0.95821727, 0.92200557])